/**
 * Redes Integradas de Telecomunicacoes I
 * MIEEC 2017/2018
 *
 * Router.java
 *
 * Main class and graphic interface class with auxiliar functions
 *
 * Created on 7 de Setembro de 2017, 16:00
 * @author  Luis Bernardo
 */

package router;

import java.io.*;
import java.net.*;


/**
 * Main class and graphic interface class with auxiliar functions
 */
public class Router extends javax.swing.JFrame implements Log {
    
    /** Type codes of the packets */
    public final static byte PKT_HELLO = 1;    
    public final static byte PKT_BYE = 2;    
    public final static byte PKT_ROUTE = 3;  
    public final static byte PKT_DATA = 4;
    /** Maximum valid distance for a route, in the Dijkstra algorithm */
    public final static int MAX_DISTANCE = 39;
    /** Maximum number of areas */
    public final static int MAX_N_AREA = 9;
    /** Maximum path length for a DATA packet */
    public final static int MAX_PATH_LEN = 10;
    

    /**
     * Constructor - creates a new form router
     */
    public Router() {
        // Start main window
        initComponents();
        // Start Neighbour list
        neig= new NeighbourList(neigTable.getRowCount(), this);
        
        ds= null;
        daemon= null;
        route= null;
        data_seq= 1;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editPort = new javax.swing.JTextField();
        tbuttonActive = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        neigTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonRem = new javax.swing.JButton();
        buttonMod = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        editNeigName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        editNeigDist = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        editNeigIP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editNeigPort = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        checkSndIfChanges = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        editPeriod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        editMinInterval = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        editIPMulticast = new javax.swing.JTextField();
        editPortMulticast = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        editAreas = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        routingTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        buttonSend = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        editDestName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editMessage = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textLog = new javax.swing.JTextArea();

        setTitle("T1 RIT1 by ?????, ????? and ?????");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(375, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(375, 35));

        jLabel1.setText("Name");
        jPanel1.add(jLabel1);

        editName.setText("A");
        editName.setMaximumSize(new java.awt.Dimension(25, 19));
        editName.setMinimumSize(new java.awt.Dimension(18, 19));
        editName.setPreferredSize(new java.awt.Dimension(25, 19));
        jPanel1.add(editName);

        jLabel2.setText("IP");
        jPanel1.add(jLabel2);

        editIP.setText("127.0.0.1");
        editIP.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(editIP);

        jLabel3.setText("Port");
        jPanel1.add(jLabel3);

        editPort.setText("20000");
        editPort.setMaximumSize(new java.awt.Dimension(60, 20));
        editPort.setMinimumSize(new java.awt.Dimension(45, 20));
        editPort.setPreferredSize(new java.awt.Dimension(55, 20));
        jPanel1.add(editPort);

        tbuttonActive.setText("Active");
        tbuttonActive.setMargin(new java.awt.Insets(1, 2, 1, 2));
        tbuttonActive.setPreferredSize(new java.awt.Dimension(73, 25));
        tbuttonActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbuttonActiveActionPerformed(evt);
            }
        });
        jPanel1.add(tbuttonActive);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(360, 140));
        jPanel2.setMinimumSize(new java.awt.Dimension(320, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 75));
        jPanel2.setLayout(null);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 140));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 70));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 70));

        neigTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "IP", "Port", "Distance", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        neigTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                neigTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(neigTable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 5, 350, 70);

        getContentPane().add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(320, 35));
        jPanel3.setMinimumSize(new java.awt.Dimension(320, 35));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 35));

        buttonAdd.setText("Add Neig");
        buttonAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonAdd.setMaximumSize(new java.awt.Dimension(90, 26));
        buttonAdd.setMinimumSize(new java.awt.Dimension(80, 25));
        buttonAdd.setPreferredSize(new java.awt.Dimension(90, 25));
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel3.add(buttonAdd);

        buttonRem.setText("Rem. Neig");
        buttonRem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonRem.setMaximumSize(new java.awt.Dimension(90, 26));
        buttonRem.setMinimumSize(new java.awt.Dimension(90, 25));
        buttonRem.setPreferredSize(new java.awt.Dimension(90, 26));
        buttonRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemActionPerformed(evt);
            }
        });
        jPanel3.add(buttonRem);

        buttonMod.setText("Mod. Neig");
        buttonMod.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonMod.setMaximumSize(new java.awt.Dimension(90, 26));
        buttonMod.setMinimumSize(new java.awt.Dimension(80, 25));
        buttonMod.setPreferredSize(new java.awt.Dimension(90, 26));
        buttonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModActionPerformed(evt);
            }
        });
        jPanel3.add(buttonMod);

        getContentPane().add(jPanel3);

        jPanel8.setMaximumSize(new java.awt.Dimension(375, 30));
        jPanel8.setPreferredSize(new java.awt.Dimension(375, 30));

        jLabel11.setText(" Name");
        jPanel8.add(jLabel11);

        editNeigName.setText("B");
        editNeigName.setMaximumSize(new java.awt.Dimension(25, 28));
        editNeigName.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel8.add(editNeigName);

        jLabel10.setText(" Dist.");
        jPanel8.add(jLabel10);

        editNeigDist.setText("1");
        editNeigDist.setMaximumSize(new java.awt.Dimension(25, 20));
        editNeigDist.setMinimumSize(new java.awt.Dimension(20, 20));
        editNeigDist.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel8.add(editNeigDist);

        jLabel8.setText("IP");
        jPanel8.add(jLabel8);

        editNeigIP.setText("127.1.1.1");
        editNeigIP.setMaximumSize(new java.awt.Dimension(200, 20));
        editNeigIP.setMinimumSize(new java.awt.Dimension(80, 20));
        editNeigIP.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel8.add(editNeigIP);

        jLabel9.setText("Port");
        jPanel8.add(jLabel9);

        editNeigPort.setText("20000");
        editNeigPort.setMaximumSize(new java.awt.Dimension(55, 20));
        editNeigPort.setMinimumSize(new java.awt.Dimension(45, 20));
        editNeigPort.setPreferredSize(new java.awt.Dimension(55, 20));
        jPanel8.add(editNeigPort);

        getContentPane().add(jPanel8);

        jPanel7.setMaximumSize(new java.awt.Dimension(400, 30));
        jPanel7.setMinimumSize(new java.awt.Dimension(307, 30));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 30));

        checkSndIfChanges.setText("Send if changes");
        checkSndIfChanges.setMaximumSize(new java.awt.Dimension(150, 23));
        checkSndIfChanges.setMinimumSize(new java.awt.Dimension(130, 23));
        checkSndIfChanges.setPreferredSize(new java.awt.Dimension(140, 23));
        jPanel7.add(checkSndIfChanges);

        jLabel6.setText("Period");
        jPanel7.add(jLabel6);

        editPeriod.setText("10");
        editPeriod.setMaximumSize(new java.awt.Dimension(35, 28));
        editPeriod.setMinimumSize(new java.awt.Dimension(14, 19));
        editPeriod.setPreferredSize(new java.awt.Dimension(30, 19));
        jPanel7.add(editPeriod);

        jLabel7.setText("Min Interval");
        jPanel7.add(jLabel7);

        editMinInterval.setText("0");
        editMinInterval.setMaximumSize(new java.awt.Dimension(25, 19));
        editMinInterval.setMinimumSize(new java.awt.Dimension(20, 19));
        editMinInterval.setPreferredSize(new java.awt.Dimension(25, 19));
        jPanel7.add(editMinInterval);

        getContentPane().add(jPanel7);

        jPanel9.setMaximumSize(new java.awt.Dimension(375, 30));
        jPanel9.setMinimumSize(new java.awt.Dimension(330, 30));
        jPanel9.setPreferredSize(new java.awt.Dimension(375, 30));

        jLabel13.setText("Multicast");
        jPanel9.add(jLabel13);

        editIPMulticast.setText("228.5.6.7");
        editIPMulticast.setMaximumSize(new java.awt.Dimension(75, 19));
        editIPMulticast.setMinimumSize(new java.awt.Dimension(65, 19));
        editIPMulticast.setPreferredSize(new java.awt.Dimension(75, 19));
        jPanel9.add(editIPMulticast);

        editPortMulticast.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        editPortMulticast.setText("19000");
        editPortMulticast.setMaximumSize(new java.awt.Dimension(66, 19));
        editPortMulticast.setMinimumSize(new java.awt.Dimension(36, 19));
        editPortMulticast.setPreferredSize(new java.awt.Dimension(55, 19));
        jPanel9.add(editPortMulticast);

        jLabel12.setText("Areas:");
        jPanel9.add(jLabel12);

        editAreas.setText("0");
        editAreas.setMaximumSize(new java.awt.Dimension(50, 19));
        editAreas.setMinimumSize(new java.awt.Dimension(20, 19));
        editAreas.setPreferredSize(new java.awt.Dimension(50, 19));
        jPanel9.add(editAreas);

        getContentPane().add(jPanel9);

        jPanel4.setMaximumSize(new java.awt.Dimension(320, 200));
        jPanel4.setMinimumSize(new java.awt.Dimension(320, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(320, 120));
        jPanel4.setLayout(null);

        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(300, 400));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 115));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 115));

        routingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Destination", "Router", "Area", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        routingTable.setMaximumSize(new java.awt.Dimension(300, 500));
        routingTable.setMinimumSize(new java.awt.Dimension(300, 400));
        jScrollPane2.setViewportView(routingTable);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 5, 300, 115);

        getContentPane().add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(400, 35));
        jPanel5.setMinimumSize(new java.awt.Dimension(320, 35));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 35));

        buttonSend.setText("Send");
        buttonSend.setMargin(new java.awt.Insets(2, 5, 2, 5));
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        jPanel5.add(buttonSend);

        jLabel4.setText("Dest:");
        jPanel5.add(jLabel4);

        editDestName.setText("A");
        editDestName.setMaximumSize(new java.awt.Dimension(25, 20));
        editDestName.setMinimumSize(new java.awt.Dimension(16, 20));
        editDestName.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel5.add(editDestName);

        jLabel5.setText("Msg:");
        jPanel5.add(jLabel5);

        editMessage.setText("test 1");
        editMessage.setMaximumSize(new java.awt.Dimension(90, 19));
        editMessage.setMinimumSize(new java.awt.Dimension(90, 19));
        editMessage.setPreferredSize(new java.awt.Dimension(90, 19));
        jPanel5.add(editMessage);

        buttonClear.setText("Clear");
        buttonClear.setMargin(new java.awt.Insets(2, 5, 2, 5));
        buttonClear.setPreferredSize(new java.awt.Dimension(60, 29));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel5.add(buttonClear);

        getContentPane().add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(320, 180));
        jPanel6.setMinimumSize(new java.awt.Dimension(320, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(320, 180));
        jPanel6.setLayout(null);

        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane3.setMaximumSize(new java.awt.Dimension(301, 175));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(301, 100));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(301, 175));

        textLog.setEditable(false);
        textLog.setColumns(20);
        textLog.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textLog.setMaximumSize(new java.awt.Dimension(180, 800));
        textLog.setMinimumSize(new java.awt.Dimension(180, 100));
        textLog.setPreferredSize(new java.awt.Dimension(180, 800));
        textLog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textLogKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(textLog);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(9, 5, 301, 175);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handle key pressing in the log window
     * @param evt graphical event
     */
    private void textLogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLogKeyPressed
        if (evt.getKeyChar() == 's') {
            write_statistics();
        }
        if (evt.getKeyChar() == 'z') {
            zero_statistics();
        }
    }//GEN-LAST:event_textLogKeyPressed

    /** 
     * Updates edit windows with selected line data 
     * @param evt graphical event
     */
    private void neigTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_neigTableMouseClicked
        int row= neigTable.getSelectedRow();
        if (row == -1) { // Line not selected
            return;
        }
        for (int i= 0; i<4; i++) {
            String s= (String)neigTable.getValueAt(row, i);
            if (s == null) {
                return;
            }
            switch (i) {
                case 0: editNeigName.setText(s); break;
                case 1: editNeigIP.setText(s); break;
                case 2: editNeigPort.setText(s); break;
                case 3: editNeigDist.setText(s); break;
            }
        }
    }//GEN-LAST:event_neigTableMouseClicked

    /** 
     * Handle "Clear" button - clear the log window contents 
     * @param evt graphical event
     */
    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        textLog.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    /**
     * Handle "Send" button - send a DATA test packet 
     * @param evt graphical event
     */
    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        synchronized (main_lock) {
            route.send_data_packet(local_name(), data_seq++,
                editDestName.getText().charAt(0), editMessage.getText(), "");
        }
    }//GEN-LAST:event_buttonSendActionPerformed

    /** 
     * Handle button "Mod. Neig" - changes the distance to the Neighbour 
     * @param evt graphical event
     */
    private void buttonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        if (neig.locate_neig(editNeigName.getText().charAt(0)) == null) {
            Log("Invalid neighbour\n");
            return;
        }
        try {
            synchronized (main_lock) {
                Neighbour n= neig.locate_neig(editNeigName.getText().charAt(0));
                String n_areas= (n!=null) && (n.area!=null) ? n.area : null;
                if (neig.update_neig(editNeigName.getText().charAt(0), 
                              editNeigIP.getText(), 
                              Integer.parseInt(editNeigPort.getText()),
                              Integer.parseInt(editNeigDist.getText()), null
                              )) { /***************/
                    neig.refresh_table(neigTable);
                    if (sendIfChanges()) {
                        route.network_changed(n_areas);
                    }
                }
            }
        }
        catch (NumberFormatException e) { 
            Log("Invalid number\n");
        }
    }//GEN-LAST:event_buttonModActionPerformed

    /** 
     * Handle button "Rem. neig" - Removes a Neighbour from the list 
     * @param evt graphical event
     */
    private void buttonRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        try {
            Neighbour n= neig.locate_neig(editNeigName.getText().charAt(0));
            if (n == null) {
                Log("Invalid neighbour\n");
                return;
            }
            String areas= (n.area != null) ? new String(n.area) : "";
            synchronized (main_lock) {
                if (neig.del_neig(editNeigName.getText().charAt(0), true, ds)) {
                    neig.refresh_table(neigTable);
                    if (sendIfChanges() && !areas.equals("")) {
                        route.network_changed(areas);
                    }
                }
            }
        }
        catch(Exception e) {
            System.err.println("Exception in 'Remove neighbour button:"+e);
        }
    }//GEN-LAST:event_buttonRemActionPerformed

    /** 
     * Handle "Add Neig" button - Adds a new Neighbour to the list 
     * @param evt graphical event
     */
    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        String new_name= editNeigName.getText();
        if (new_name.length()>1 || !Character.isUpperCase(new_name.charAt(0))) {
            Log("Invalid name '"+new_name+"'\n");
            return;
        }
        if (neig.locate_neig(new_name.charAt(0)) != null) {
            Log("Duplicate name\n");
            return;            
        }
        synchronized (main_lock) {
            try {
                if (neig.add_neig(new_name.charAt(0), 
                              editNeigIP.getText(), 
                              Integer.parseInt(editNeigPort.getText()),
                              Integer.parseInt(editNeigDist.getText()),
                              ds, null)) {
                    neig.refresh_table(neigTable);
                }
            }
            catch (NumberFormatException e) { 
                Log("Invalid number\n");
            }
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    /** 
     * Handle "Active" button - Activates or stops the Router 
     * @param evt graphical event
     */
    private void tbuttonActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbuttonActiveActionPerformed
        if (tbuttonActive.isSelected()) {
            // Start Router
            boolean active= false;
            try {
                int port= Integer.parseInt(editPort.getText());
                char c= editName.getText().charAt(0);              
                int period= Integer.parseInt(editPeriod.getText());
                int minInterval= Integer.parseInt(editMinInterval.getText());
                int mport= Integer.parseInt (editPortMulticast.getText());
                String areas= local_areas();
                do {
                    try {
                        ds= new DatagramSocket(port);
                        active= true;
                    }
                    catch (SocketException se) {
                        // Skip to next letter
                        port++;
                        c++;
                    }
                } while (!active && (c<='Z'));
                
                if (!active) {
                    Log("All letters ('A'-'Z') occupied\n");
                    tbuttonActive.setSelected(false);
                    return;
                }
                 // Update edit boxes
                editPort.setText(""+port);
                editName.setText(""+c);
                editIP.setText(InetAddress.getLocalHost().getHostAddress());
                editDestName.setText (""+c);
                if (c<'Z') {
                    c++;
                } else {
                    c--;
                }
                editNeigName.setText(""+c);
                editNeigPort.setText(""+(port+1));
                editNeigIP.setText(InetAddress.getLocalHost().getHostAddress());

                // Start Routing timer
                route= new Routing(local_name(), neig, period, minInterval, areas,
                        editIPMulticast.getText(), mport, this, ds, routingTable);
                if (!route.start()) {
                    Log("Failed to boot the routing object\n");
                    ds.close();
                    ds= null;
                    tbuttonActive.setSelected(false);
                    return;
                }
                // Start daemon thread
                daemon= new Daemon(ds);
                daemon.start();
                // Lock entry windows
                editName.setEditable(false);                
                editPort.setEditable(false);
                editIP.setEditable(false);
                checkSndIfChanges.setEnabled(false);
                editPeriod.setEditable(false);
                editMinInterval.setEditable(false);
                editPortMulticast.setEditable(false);
                editIPMulticast.setEditable(false);
                editAreas.setEditable(false);
                zero_statistics();
            }
            catch (UnknownHostException e) {
                Log("Localhost Unknown: "+e+"\n");
                tbuttonActive.setSelected(false);
            }
            catch (NumberFormatException e) {
                Log("Port number or period invalid: "+e+"\n");
                tbuttonActive.setSelected(false);
            }
            
        } else {
            // Stop Router
            stop_router();
        }
    }//GEN-LAST:event_tbuttonActiveActionPerformed
    
    /**
     * Handle the exit window event - exits the application
     * @param evt graphical event
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        if (tbuttonActive.isSelected()) {
            stop_router();
        }
        System.exit(0);
    }//GEN-LAST:event_exitForm

 
    /**
     * Returns true if SndIfChanges is selected
     * @return true if check box is selected
     */
    public boolean sendIfChanges() {
        return checkSndIfChanges.isSelected();
    }
    
    /** 
     * Stops the Router 
     */
    private void stop_router() {
        if (daemon != null) {
            daemon.stopRunning();
            daemon= null;
        }
        if (route != null) {
            route.stop();
            route= null;
        }
        if (ds != null) {
            neig.clear_BYE(ds);
            neig.refresh_table(neigTable);
            ds.close();
            ds= null;
        }
        if (tbuttonActive.isSelected()) {
            Log("Router "+local_name()+" stopped\n");
        }
        editName.setEditable(true);
        editPort.setEditable(true);
        editIP.setEditable(true);
        checkSndIfChanges.setEnabled(true);
        editPeriod.setEditable(true);
        editMinInterval.setEditable(true);
        editPortMulticast.setEditable(true);
        editIPMulticast.setEditable(true);
        editAreas.setEditable(true);
    }

    
    /**
     * Get the node name from the form
     * @return local name (address)
     */
    public char local_name() {
        try {
            return editName.getText().charAt(0);
        }
        catch(Exception e) {
            Log("Local name error: "+e);
        }
        return '*';
    }
        
    /**
     * Test if nm is the local name
     * @param nm test name
     * @return true if names are equal, false otherwise
     */
    public boolean is_local_name(char nm) {
        return (nm == local_name());
    }

    /**
     * Get a string with the list of local areas from the form
     * @return string with local areas 
     */
    public String local_areas() {
        String res= editAreas.getText();
        if (res.length() <1) {
            Log("Invalid list of Areas\n");
            return null;
        }
        for (int i= 0; i<res.length(); i++) {
            if ((res.charAt(i)<'0') || (res.charAt(i)>'9')) {
                Log("Invalid area number ("+res.charAt(i)+")\n");
                return null;
            }
            if (res.substring(0, i).indexOf(res.charAt(i)) != -1) {
                Log("Duplicate area number ("+res.charAt(i)+")\n");
                return null;
            }
        }
        if ((res.length()>1) && !res.contains("0")) {
            Log("Invalid area number: an area border router must belong to area 0\n");
            return null;
        }
        return res;
    }
    
    
    
    /** 
     * Thread that handles socket events 
     */
    public class Daemon extends Thread {
        volatile boolean keepRunning= true;
        DatagramSocket ds;
        
        // Constructor
        Daemon(DatagramSocket ds) {
            this.ds= ds;
        }
        
        // Thread main function
        @Override
        public void run() {
            byte [] buf= new byte[8096];
            DatagramPacket dp= new DatagramPacket(buf, buf.length);
            try {
                while (keepRunning) {
                    try {
                        ds.receive(dp);
                        ByteArrayInputStream BAis= 
                            new ByteArrayInputStream(buf, 0, dp.getLength());
                        DataInputStream dis= new DataInputStream(BAis);
                        System.out.println("Received packet ("+dp.getLength()+
                            ") from " + dp.getAddress().getHostAddress() +
                            ":" +dp.getPort());
                        
                        synchronized (main_lock) {
                            process_packet(dp, dis);
                        }
                    }
                    catch (SocketException se) {
                        if (keepRunning) {
                            Log("recv UDP SocketException : " + se + "\n");
                        }
                    }
                }
            }
            catch(IOException e) {
                if (keepRunning) {
                    Log("IO exception receiving data from socket : " + e);
                }
            }
        }
        
        // Stop thread
        public void stopRunning() {
            keepRunning= false;
        }
    }


    
    /**
     * handle incoming packets, decoding and processing HELLO and BYE packets
     * @param dp    datagram packet
     * @param dis   input stream
     * @return true if packet was processed with success, false otherwise
     */
    boolean process_packet(DatagramPacket dp, DataInputStream dis) {
        byte code;
        char sender;
        try {
            code= dis.readByte();     // read code
            sender= dis.readChar();   // read sender id
            String ip= dp.getAddress().getHostAddress();  // Get sender address            
            if (ip.startsWith("127.")) {
                try {
                    ip= InetAddress.getLocalHost().getHostAddress();
                }
                catch (UnknownHostException e) {
                    Log("Error converting address '127.*'\n");
                    return false;
                }
            }
            
            switch(code) {
                case PKT_HELLO:
                    Log("PKT_HELLO("+sender+")\n");
                    HELLO_rcv++;
                    // Update values
                    int dist= dis.readInt();
                    int len= dis.readInt();
                    if (len>MAX_N_AREA) {
                        Log("Invalid area list's length\n");
                        return false;
                    }
                    String area= "";
                    for (int i=0; i<len; i++) {
                        area += dis.readChar();
                    }

                    if (dis.available() != 0) {
                        Log("Packet too long\n");
                        return false;
                    }
                    if (tbuttonActive.isSelected()) {
                        boolean ok= neig.add_neig(sender, ip, dp.getPort(), 
                            dist, ds, area);
                        if (ok) {
                            neig.refresh_table(neigTable);
                            if (sendIfChanges()) {
                                route.network_changed(area);
                            }
                        }
                    }
                    break;
                    
                case PKT_BYE:
                    Log("PKT_BYE("+sender+")\n");
                    BYE_rcv++;
                    if (dis.available() != 0) {
                        Log("Packet too long\n");
                        return false;
                    }
                    if (tbuttonActive.isSelected()) {
                        Neighbour n= neig.locate_neig(sender);
                        String areas= (n!=null) ? n.area : null;
                        boolean ok= neig.del_neig(sender, false, ds);
                        if (ok) {
                            neig.refresh_table(neigTable);
                            if (sendIfChanges()) {
                                route.network_changed(areas);
                            }
                        }
                    }
                    break;
                    
                case PKT_ROUTE:
                    ROUTE_rcv++; 
                    return route.process_ROUTE(sender, dp, ip, dis);
                    
                case PKT_DATA:
                    DATA_rcv++;
                    return route.process_DATA(sender, dp, ip, dis);
                    
                default:
                    Log("Invalid packet code ("+code+")\n");
                    INVALID_rcv++;
                    return false;
                }
            }
            catch(IOException e) {
                Log("Packet too short\n");
                return false;
            }
            return true;
    }

    
   /**
     * main function of the Router program
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Router().setVisible(true);
    }
    
    /**
     * Write messages in the log window and in the command line
     * @param s  message to write
     */
    @Override
    public void Log(final java.lang.String s) {
        textLog.append(s);
        System.out.print(s);
    }         

    /** 
     * Clear statistics 
     */
    public void zero_statistics() {
        HELLO_snt= 0;
        HELLO_rcv= 0;
        BYE_snt= 0;
        BYE_rcv= 0;
        ROUTE_loc= 0;
        ROUTE_snt= 0;
        ROUTE_rcv= 0;
        DATA_snt= 0;
        DATA_rcv= 0;
        INVALID_rcv= 0;
        Dijkstra_cnt= 0;        
    }
    
    /** 
     * Write statistics 
     */
    public void write_statistics() {
        Log("****Statistics**********************************************\n"+
            "HELLO snt:"+HELLO_snt+" rcv:"+HELLO_rcv+
            "; BYE snt:"+BYE_snt+" rcv:"+BYE_rcv+
            "\nROUTE loc:"+ROUTE_loc+" snt:"+ROUTE_snt+" rcv:"+ROUTE_rcv+
            "\nDATA snt:"+DATA_snt+" rcv:"+DATA_rcv+
            "; Invalid rcv:"+INVALID_rcv+"; Dijkstra cnt:"+Dijkstra_cnt+"\n"+
            "************************************************************\n");
    }
    
    ////////////////////////////////////////////////////////////////////
    
    /** Synchronization lock */
    public final Integer main_lock= new Integer(0);
    
    /** Datagram socket */
    private DatagramSocket ds;
    /** Socket daemon */
    private Daemon daemon;
    /** meighbour list */
    private final NeighbourList neig;
    /** Routing object */
    private Routing route;
    /** Data sequence counter */
    private int data_seq;
    
    /* Statistical counters */
    public int HELLO_snt;
    public int HELLO_rcv;
    public int BYE_snt;
    public int BYE_rcv;
    public int ROUTE_loc;   // only counts local Routing
    public int ROUTE_snt;
    public int ROUTE_rcv;
    public int DATA_snt;
    public int DATA_rcv;
    public int INVALID_rcv;
    public int Dijkstra_cnt;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton buttonAdd;
    javax.swing.JButton buttonClear;
    javax.swing.JButton buttonMod;
    javax.swing.JButton buttonRem;
    javax.swing.JButton buttonSend;
    javax.swing.JCheckBox checkSndIfChanges;
    javax.swing.JTextField editAreas;
    javax.swing.JTextField editDestName;
    javax.swing.JTextField editIP;
    javax.swing.JTextField editIPMulticast;
    javax.swing.JTextField editMessage;
    javax.swing.JTextField editMinInterval;
    javax.swing.JTextField editName;
    javax.swing.JTextField editNeigDist;
    javax.swing.JTextField editNeigIP;
    javax.swing.JTextField editNeigName;
    javax.swing.JTextField editNeigPort;
    javax.swing.JTextField editPeriod;
    javax.swing.JTextField editPort;
    javax.swing.JTextField editPortMulticast;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel8;
    javax.swing.JPanel jPanel9;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JTable neigTable;
    javax.swing.JTable routingTable;
    javax.swing.JToggleButton tbuttonActive;
    javax.swing.JTextArea textLog;
    // End of variables declaration//GEN-END:variables
  
}
